-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 21:05:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bbddapppro001
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bbddapppro001
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbddapppro001` DEFAULT CHARACTER SET utf8 ;
USE `bbddapppro001` ;

-- -----------------------------------------------------
-- Table `bbddapppro001`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddapppro001`.`group` (
  `idgroup` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  `currency` VARCHAR(3) NOT NULL,
  `icon` INT NOT NULL,
  PRIMARY KEY (`idgroup`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddapppro001`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddapppro001`.`activity` (
  `idactivity` INT NOT NULL AUTO_INCREMENT,
  `date_activity` DATETIME NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `idgroup` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `icon` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`idactivity`),
  INDEX `FK_Activity_Group_idx` (`idgroup` ASC) INVISIBLE,
  CONSTRAINT `FK_Activity_Group`
    FOREIGN KEY (`idgroup`)
    REFERENCES `bbddapppro001`.`group` (`idgroup`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 516
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddapppro001`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddapppro001`.`invoice` (
  `idinvoice` INT NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(255) NOT NULL,
  `type` VARCHAR(16) NOT NULL,
  `date` DATE NOT NULL,
  `provider` VARCHAR(255) NULL DEFAULT NULL,
  `start_period` DATE NULL DEFAULT NULL,
  `end_period` DATE NULL DEFAULT NULL,
  `consumption` DOUBLE NULL DEFAULT '0',
  `amount` DOUBLE NOT NULL,
  `file` LONGTEXT NULL DEFAULT NULL,
  `filetype` INT NULL DEFAULT NULL,
  `idgroup` INT NOT NULL,
  PRIMARY KEY (`idinvoice`),
  INDEX `FK_Invoice_Group_idx` (`idgroup` ASC) VISIBLE,
  CONSTRAINT `FK_Invoice_Group`
    FOREIGN KEY (`idgroup`)
    REFERENCES `bbddapppro001`.`group` (`idgroup`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 205
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddapppro001`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddapppro001`.`user` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `token` TEXT NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `date_signup` DATETIME NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddapppro001`.`shared`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddapppro001`.`shared` (
  `email` VARCHAR(255) NOT NULL,
  `idgroup` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`email`, `idgroup`),
  INDEX `FK_Shared_Group_idx` (`idgroup` ASC) VISIBLE,
  CONSTRAINT `FK_Shared_Group`
    FOREIGN KEY (`idgroup`)
    REFERENCES `bbddapppro001`.`group` (`idgroup`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Shared_User`
    FOREIGN KEY (`email`)
    REFERENCES `bbddapppro001`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
